'TITLE: PF Random Character Name Gen
'TARENNOVASTUDIOS
'DATE: 6.14.2019
'AUTHOR: MARK A. DUNHAM

    nomainwin
    BackgroundColor$ = "darkgreen"
    ForegroundColor$ = "black"
    NAMES = 78
    randomName$ = ""

    dim first$(NAMES)
        first$(1) = "Ton"
        first$(2) = "Sihn"
        first$(3) = "Karn"
        first$(4) = "Sintar"
        first$(5) = "Smash"
        first$(6) = "Snarl"
        first$(7) = "Hom"
        first$(8) = "Driden"
        first$(9) = "Khor"
        first$(10) = "Eli"
        first$(11) = "Farlah"
        first$(12) = "Palva"
        first$(13) = "Kriel"
        first$(14) = "Em"
        first$(15) = "Althris"
        first$(16) = "Bilshen"
        first$(17) = "Brenos"
        first$(18) = "Craglin"
        first$(19) = "Vanrissen"
        first$(20) = "Falliel"
        first$(21) = "Dor"
        first$(22) = "Gralen"
        first$(23) = "Aelis"
        first$(24) = "Nerrilis"
        first$(25) = "Gnu"
        first$(26) = "Morfall"
        first$(27) = "Brimson"
        first$(28) = "Tenneran"
        first$(29) = "Porgus"
        first$(30) = "Salinnas"
        first$(31) = "Valkren"
        first$(32) = "Skyvor"
        first$(33) = "Remilaria"
        first$(34) = "Slyth"
        first$(35) = "Duriel"
        first$(36) = "Zartan"
        first$(37) = "Grimface"
        first$(38) = "Overhn"
        first$(39) = "Krick"
        first$(40) = "Calfen"
        first$(41) = "Alpheial"
        first$(42) = "Wrex"
        first$(43) = "Baldrin"
        first$(44) = "Henric"
        first$(45) = "Gorthok"
        first$(46) = "Telvin"
        first$(47) = "Qwilenth"
        first$(48) = "Riventin"
        first$(49) = "Hargus"
        first$(50) = "Walthern"
        first$(51) = "Vorthor"
        first$(52) = "Nightskin"
        first$(53) = "Simithten"
        first$(54) = "Hilfren"
        first$(55) = "Oville"
        first$(56) = "Alfrhen"
        first$(57) = "Oxnif"
        first$(58) = "Gulphen"
        first$(59) = "Arshen"
        first$(60) = "Korfam"
        first$(61) = "Iffsy"
        first$(62) = "Vilton"
        first$(63) = "Dirge"
        first$(64) = "Hiberus"
        first$(65) = "Encil"
        first$(66) = "Korelon"
        first$(67) = "Thistlefoot"
        first$(68) = "Gurdor"
        first$(69) = "Astion"
        first$(70) = "Tyraleus"
        first$(71) = "Wilerran"
        first$(72) = "Valadrien"
        first$(73) = "Gort"
        first$(74) = "Illsain"
        first$(75) = "Jorien"
        first$(76) = "Wrexitta"
        first$(77) = "Vrax"
        first$(78) = "Falladhai"

    dim last$(NAMES)
        last$(1) = "Snarljammer"
        last$(2) = "Sneakfoot"
        last$(3) = "Highkick"
        last$(4) = "Pathmaker"
        last$(5) = "Brokenfang"
        last$(6) = "Hurtslater"
        last$(7) = "the Unmovable"
        last$(8) = "the Merciless"
        last$(9) = "Shatteredhelm"
        last$(10) = "Soggybottom"
        last$(11) = "Bramblebrush"
        last$(12) = "Pridesworn"
        last$(13) = "Hookheart"
        last$(14) = "Ironmold"
        last$(15) = "Seaweather"
        last$(16) = "Nightember"
        last$(17) = "Darkshadow"
        last$(18) = "Stormaxe"
        last$(19) = "Featherhall"
        last$(20) = "Whisperfall"
        last$(21) = "Shattershield"
        last$(22) = "Fireflint"
        last$(23) = "Diredread"
        last$(24) = "Oakbark"
        last$(25) = "Broketusk"
        last$(26) = "Lightstave"
        last$(27) = "Bloodscale"
        last$(28) = "Pikeshade"
        last$(29) = "Heartfist"
        last$(30) = "Swiftclaw"
        last$(31) = "Marshtoe"
        last$(32) = "Hammerstone"
        last$(33) = "Vaas"
        last$(34) = "Nightblaze"
        last$(35) = "Brightforge"
        last$(36) = "Hoofshaper"
        last$(37) = "Fleshmasher"
        last$(38) = "Mistbellows"
        last$(39) = "Brokensnap"
        last$(40) = "Thorngrower"
        last$(41) = "Planeshaper"
        last$(42) = "Metalbender"
        last$(43) = "Ashbringer"
        last$(44) = "Thistlegrinder"
        last$(45) = "Chainbreaker"
        last$(46) = "the Arrowed"
        last$(47) = "Starsheen"
        last$(48) = "Softshoe"
        last$(49) = "Hammerflat"
        last$(50) = "Willspender"
        last$(51) = "Lightscreamer"
        last$(52) = "Wolfbane"
        last$(53) = "Fireforge"
        last$(54) = "Moldenglass"
        last$(55) = "Hornsnatcher"
        last$(56) = "Hayfeaver"
        last$(57) = "Hiffleburn"
        last$(58) = "Hemroy"
        last$(59) = "Windraider"
        last$(60) = "Hellspire"
        last$(61) = "Irespark"
        last$(62) = "Briarback"
        last$(63) = "Blightstone"
        last$(64) = "Flax"
        last$(65) = "Brandybuck"
        last$(66) = "Whiteriver"
        last$(67) = "Shorthunt"
        last$(68) = "Mudgrub"
        last$(69) = "Darklily"
        last$(70) = "Ranifort"
        last$(71) = "Lofthelm"
        last$(72) = "Foerender"
        last$(73) = "Spinereaver"
        last$(74) = "Mortecall"
        last$(75) = "Hast"
        last$(76) = "Oakenblur"
        last$(77) = "Stoneburn"
        last$(78) = "Tornbolt"

[Main]
    WindowWidth = 320
    WindowHeight = 240
    UpperLeftX = int((DisplayWidth - WindowWidth)/2)
    UpperLeftY = int((DisplayHeight - WindowHeight)/2)

    button #Main.GenBtn1, "Generate",[GenName],UL,105,50,100,25
    textbox #Main.NameTb1, 35,80,250,25

    open "Pathfinder Random Name Generator" for window_nf as #Main
    #Main, "trapclose [Main.Quit]"
    #Main, "font Arial 0 0 bold"
    #Main.NameTb1, "!disable"

    wait

[GenName]
    firstName = (int(rnd(1) * NAMES) + 1)
    lastName = (int(rnd(1) * NAMES) + 1)

    randomName$ = first$(firstName) + " " + last$(lastName)
    #Main.NameTb1, randomName$

    wait

[Main.Quit]
    close #Main
    end
    wait
